# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 19:33
from __future__ import unicode_literals

import classifier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_auto_20171215_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='image',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to=classifier.models.path_and_rename),
        ),
    ]
